package org.teww.tew.core.repo

import org.teww.tew.core.R
import org.teww.tew.core.model.AppealState
import org.teww.tew.core.model.Comment
import org.teww.tew.core.model.Memo
import org.teww.tew.core.model.Moderation
import org.teww.tew.core.model.ModerationState

// GENERATED by android/tools/generate-seed-audio.sh — do not edit by hand.
//
// Every duration here was measured from the file it names. Editing one by hand
// makes the app announce a length the audio does not have, and there is no test
// that can catch that because the audio is the ground truth.
//
// Change the transcripts in the script and re-run it.

/**
 * The memos the app shows when no server address is set.
 *
 * Audio is bundled in the APK as raw resources and addressed with
 * `rawresource://`, which Media3 resolves without a network. That is the whole
 * point: a tester with a phone, no server and no signal can still open the app
 * and hear a feed.
 *
 * These transcripts are the same ones the backend seeds, so switching between
 * built-in memos and a real server does not change what the tester is looking
 * at — only where it came from.
 */
fun sampleMemos(): List<Memo> = listOf(
    Memo(
        id = "m1",
        authorUsername = "amina",
        audioUrl = rawResourceUri(R.raw.seed_m1),
        durationMs = 9919,
        postedAtEpochSeconds = minutesAgo(4),
        transcript = "Good morning everyone. I walked to the market on my own today for the first time since I moved here. I am still shaking a bit, but I did it.",
        likedByMe = false,
        moderation = Moderation.visible,
    ),
    Memo(
        id = "m2",
        authorUsername = "joseph",
        audioUrl = rawResourceUri(R.raw.seed_m2),
        durationMs = 7192,
        postedAtEpochSeconds = minutesAgo(19),
        transcript = "Does anyone else find the bus announcements too quiet? I keep missing my stop and having to walk back.",
        likedByMe = false,
        moderation = Moderation.visible,
    ),
    Memo(
        id = "m3",
        authorUsername = "fatima",
        audioUrl = rawResourceUri(R.raw.seed_m3),
        durationMs = 8003,
        postedAtEpochSeconds = minutesAgo(47),
        transcript = "My daughter recorded her school song for me this morning. I have listened to it about nine times now. I am not sorry.",
        likedByMe = false,
        moderation = Moderation.visible,
    ),
    Memo(
        id = "m4",
        authorUsername = "daniel",
        audioUrl = rawResourceUri(R.raw.seed_m4),
        durationMs = 9703,
        postedAtEpochSeconds = minutesAgo(96),
        transcript = "Question for the group. What is your trick for telling shampoo and conditioner apart? I have tried elastic bands and I keep getting it wrong.",
        likedByMe = false,
        moderation = Moderation.visible,
    ),
    Memo(
        id = "m5",
        authorUsername = "grace",
        audioUrl = rawResourceUri(R.raw.seed_m5),
        durationMs = 8460,
        postedAtEpochSeconds = minutesAgo(140),
        transcript = "I just wanted to say that hearing other people voices in the evening helps more than I expected it to. That is all. Goodnight.",
        likedByMe = false,
        moderation = Moderation.visible,
    ),
    Memo(
        id = "m6",
        authorUsername = "samuel",
        audioUrl = rawResourceUri(R.raw.seed_m6),
        durationMs = 4180,
        postedAtEpochSeconds = minutesAgo(200),
        transcript = "Rain on a tin roof. That is the whole memo. Enjoy it.",
        likedByMe = false,
        moderation = Moderation.visible,
    ),
    Memo(
        id = "m7",
        authorUsername = "joseph",
        audioUrl = rawResourceUri(R.raw.seed_m7),
        durationMs = 8957,
        postedAtEpochSeconds = minutesAgo(260),
        transcript = "Following up on the bus thing. Someone suggested asking the driver to call out my stop, and it worked. Thank you whoever that was.",
        likedByMe = false,
        moderation = Moderation.visible,
    ),
    Memo(
        id = "m8",
        authorUsername = "amina",
        audioUrl = rawResourceUri(R.raw.seed_m8),
        durationMs = 7715,
        postedAtEpochSeconds = minutesAgo(320),
        transcript = "Small thing. The tactile paving outside the library has been repaired. It has been broken for two years.",
        likedByMe = false,
        moderation = Moderation.visible,
    ),
)

/**
 * What the profile screen shows. The second one is removed on purpose, so the
 * moderation reason and the appeal flow have something real to open rather
 * than an empty state nobody can test.
 */
fun sampleOwnMemos(): List<Memo> = listOf(
    Memo(
        id = "own1",
        authorUsername = "you",
        audioUrl = rawResourceUri(R.raw.seed_own1),
        durationMs = 3166,
        postedAtEpochSeconds = minutesAgo(30),
        transcript = "Testing this out. Hello from my kitchen.",
        likedByMe = false,
        moderation = Moderation.visible,
    ),
    Memo(
        id = "own2",
        authorUsername = "you",
        audioUrl = rawResourceUri(R.raw.seed_own2),
        durationMs = 5027,
        postedAtEpochSeconds = minutesAgo(400),
        transcript = "This memo was taken down, so the appeal screen has something to open.",
        likedByMe = false,
        moderation = Moderation(
            state = ModerationState.REMOVED,
            reason = "A listener reported this memo for harassment, and a moderator agreed it broke the community rules. If you think that was wrong, you can ask for another look.",
            appeal = AppealState.AVAILABLE,
        ),
    ),
)

/**
 * Replies, keyed by the memo they answer.
 *
 * Without these the comments screen opens empty in offline mode, and "listen to
 * the replies" — one of the three things a tester is asked to try — cannot be
 * tried at all.
 */
fun sampleComments(): Map<String, List<Comment>> = mapOf(
    "m2" to listOf(
        Comment(
            id = "c1",
            memoId = "m2",
            authorUsername = "grace",
            audioUrl = rawResourceUri(R.raw.seed_c1),
            durationMs = 4830,
            postedAtEpochSeconds = minutesAgo(12),
            transcript = "I have the same problem on the number nine. You are not imagining it.",
        ),
        Comment(
            id = "c2",
            memoId = "m2",
            authorUsername = "daniel",
            audioUrl = rawResourceUri(R.raw.seed_c2),
            durationMs = 4749,
            postedAtEpochSeconds = minutesAgo(8),
            transcript = "Ask the driver when you get on. Mine has never once minded.",
        ),
    ),
    "m4" to listOf(
        Comment(
            id = "c3",
            memoId = "m4",
            authorUsername = "fatima",
            audioUrl = rawResourceUri(R.raw.seed_c3),
            durationMs = 5421,
            postedAtEpochSeconds = minutesAgo(60),
            transcript = "Rubber band on the conditioner. One band, one bottle, never two.",
        ),
    ),
    "m1" to listOf(
        Comment(
            id = "c4",
            memoId = "m1",
            authorUsername = "samuel",
            audioUrl = rawResourceUri(R.raw.seed_c4),
            durationMs = 4146,
            postedAtEpochSeconds = minutesAgo(3),
            transcript = "That is a big thing, not a small one. Well done.",
        ),
    ),
)
